import Dexie, { type Table } from 'dexie';
import { v4 as uuidv4 } from 'uuid';

export interface Ledger {
  id: string;
  name: string;
  baseCurrency: string; // The default currency for the ledger
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
}

export interface Transaction {
  id: string;
  displayId?: string; // Human-readable serial number
  ledgerId: string;
  splitGroupId?: string; // Optional identifier for a multi-person advance / split expense group
  isGift?: boolean; // True if this loan transaction is a gift / grant (does not create debt / receivable / payable)
  budgetId?: string; // Optional manual budget assignment ('none' or budget id)
  amount: number; // Base currency amount
  originalAmount: number; // Original currency amount
  originalCurrency: string; // The currency code for this transaction
  exchangeRate: number; // Rate used to convert to base currency
  type: 'income' | 'expense' | 'transfer' | 'loan';
  category: string;
  accountId: string; // The account for income/expense, or the "from" account for transfer
  toAccountId?: string; // The "to" account for transfer
  transferInAmount?: number; // The actual amount received in the "to" account (for cross-currency or fees)
  note?: string;
  date: string; // ISO date string (YYYY-MM-DD)
  createdAt: string; // ISO datetime
  updatedAt: string; // ISO datetime
  deleted: boolean; // Soft delete flag for sync
}

export interface ExchangeRate {
  currency: string;
  rate: number; // Rate relative to USD (1 USD = X Currency)
  updatedAt: string;
}

export interface Category {
  id: string;
  ledgerId: string;
  name: string;
  type: 'income' | 'expense';
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
  archived?: boolean;
  isSystem?: boolean;
}

export interface Wallet {
  id: string;
  ledgerId: string;
  name: string;
  type?: 'wallet';
  group?: string; // e.g., 'cash', 'debit', 'credit', 'investment', 'credit_pay', 'other'
  isDefault: boolean;
  initialBalance?: number;
  currency?: string;
  creditLimit?: number; // 信用總額度
  statementDay?: number; // 每月帳單日 (1 - 31)
  dueDay?: number; // 每月還款日 (1 - 31)
  archived?: boolean;
  excludeFromStats?: boolean; // 排除資產統計
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
}

export interface Contact {
  id: string;
  ledgerId: string;
  name: string;
  group?: string; // e.g., 'personal', 'organization', 'family', 'friend', 'colleague', 'business', 'other'
  currency?: string;
  note?: string;
  archived?: boolean;
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
}

export interface BalanceSnapshot {
  id: string; // 複合識別碼: `${walletId}_${periodKey}`
  ledgerId: string;
  walletId: string;
  periodKey: string; // 月度標識: "YYYY-MM" (如 "2026-05")
  closingBalance: number; // 該月末以錢包原生幣種計的收盤餘額
  currency: string; // 錢包原生幣種代碼
  snapshotDate: string; // 該月最後一日日期: "YYYY-MM-DD" (如 "2026-05-31")
  transactionCount: number; // 截至該月累計參與計算的交易總筆數
  updatedAt: string;
}

// 向後相容別名：Account 即為資產錢包 (Wallet)
export type Account = Wallet;

export type BudgetPeriodType = 'monthly' | 'yearly' | 'custom' | 'unlimited';

export interface BudgetRule {
  id: string;
  ledgerId: string;
  name: string;
  amount: number;
  periodType: 'monthly' | 'yearly';
  categoryIds: string[];
  isActive: boolean;
  lastGeneratedPeriod: string; // e.g. "2026-09" or "2026"
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
}

export interface Budget {
  id: string;
  ledgerId: string;
  ruleId?: string; // Links to BudgetRule if generated by one
  name: string;
  amount: number;
  periodType: BudgetPeriodType;
  periodKey?: string; // e.g. "2026-09" for monthly, "2026" for yearly, undefined for custom
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  categoryIds?: string[];
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
  isEnded?: boolean;
  endedAt?: string; // YYYY-MM-DD when ended manually
}

export class ZenanceDatabase extends Dexie {
  ledgers!: Table<Ledger>;
  transactions!: Table<Transaction>;
  categories!: Table<Category>;
  accounts!: Table<Wallet>;
  contacts!: Table<Contact>;
  budgets!: Table<Budget>;
  budget_rules!: Table<BudgetRule>;
  exchange_rates!: Table<ExchangeRate>;
  balance_snapshots!: Table<BalanceSnapshot>;

  // 語義化別名：db.wallets 直接指向實體錢包表 db.accounts
  get wallets(): Table<Wallet> {
    return this.accounts;
  }

  constructor() {
    super('ZenanceDB');
    
    this.version(2).stores({
      transactions: 'id, date, type, updatedAt, deleted', // Indexed properties
      categories: 'id, type, isDefault, updatedAt, deleted',
    });

    this.version(3).stores({
      transactions: 'id, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, type, isDefault, updatedAt, deleted',
      accounts: 'id, isDefault, updatedAt, deleted',
    }).upgrade(async tx => {
      // Create a default Cash account during migration
      const cashAccountId = uuidv4();
      await tx.table('accounts').add({
        id: cashAccountId,
        name: 'Cash',
        isDefault: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deleted: false,
      });

      // Assign all existing transactions to this Cash account
      await tx.table('transactions').toCollection().modify(t => {
        t.accountId = cashAccountId;
      });
    });

    this.version(4).stores({
      transactions: 'id, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, type, isDefault, updatedAt, deleted',
      accounts: 'id, isDefault, updatedAt, deleted',
      budgets: 'id, startDate, endDate, updatedAt, deleted',
    });

    this.version(5).stores({
      transactions: 'id, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, type, isDefault, updatedAt, deleted',
      accounts: 'id, type, isDefault, updatedAt, deleted',
      budgets: 'id, startDate, endDate, updatedAt, deleted',
    }).upgrade(async tx => {
      // Set existing accounts to 'wallet' type
      await tx.table('accounts').toCollection().modify(a => {
        if (!a.type) a.type = 'wallet';
      });
    });

    this.version(6).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      budgets: 'id, ledgerId, startDate, endDate, updatedAt, deleted',
    }).upgrade(async tx => {
      const defaultLedgerId = uuidv4();
      const now = new Date().toISOString();
      
      // Create default ledger
      await tx.table('ledgers').add({
        id: defaultLedgerId,
        name: 'Personal',
        isDefault: true,
        createdAt: now,
        updatedAt: now,
        deleted: false,
      });

      // Migrate existing records to the default ledger
      await tx.table('transactions').toCollection().modify(t => {
        t.ledgerId = defaultLedgerId;
      });
      await tx.table('categories').toCollection().modify(c => {
        c.ledgerId = defaultLedgerId;
      });
      await tx.table('accounts').toCollection().modify(a => {
        a.ledgerId = defaultLedgerId;
      });
      await tx.table('budgets').toCollection().modify(b => {
        b.ledgerId = defaultLedgerId;
      });
    });

    this.version(7).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      budgets: 'id, ledgerId, startDate, endDate, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async tx => {
      // Default to CNY for existing ledgers based on user request
      await tx.table('ledgers').toCollection().modify(l => {
        l.baseCurrency = 'CNY';
      });
      
      // Populate transactions with originalAmount, currency and rate
      await tx.table('transactions').toCollection().modify(t => {
        t.originalAmount = t.amount;
        t.originalCurrency = 'CNY';
        t.exchangeRate = 1;
      });
    });

    this.version(8).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      budgets: 'id, ledgerId, startDate, endDate, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async tx => {
      // Add displayId for existing transactions
      await tx.table('transactions').toCollection().modify(t => {
        if (!t.displayId) {
          t.displayId = t.id.split('-')[0].toUpperCase();
        }
      });
    });

    this.version(9).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      budgets: 'id, ledgerId, startDate, endDate, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async tx => {
      // Set initialBalance to 0 for existing accounts
      await tx.table('accounts').toCollection().modify(a => {
        if (a.initialBalance === undefined) {
          a.initialBalance = 0;
        }
      });
    });

    this.version(10).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      budgets: 'id, ledgerId, startDate, endDate, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async () => {
      // Currency will be undefined for existing accounts, which falls back to ledger base currency
    });

    this.version(11).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, group, isDefault, updatedAt, deleted',
      budgets: 'id, ledgerId, startDate, endDate, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async tx => {
      await tx.table('accounts').toCollection().modify(a => {
        if (!a.group) {
          a.group = a.type === 'contact' ? 'other' : 'cash';
        }
      });
    });

    this.version(12).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, group, isDefault, archived, updatedAt, deleted',
      budgets: 'id, ledgerId, startDate, endDate, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async tx => {
      await tx.table('accounts').toCollection().modify(a => {
        if (a.archived === undefined) {
          a.archived = false;
        }
      });
    });

    this.version(13).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, group, isDefault, archived, updatedAt, deleted',
      budgets: 'id, ledgerId, periodType, startDate, endDate, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async tx => {
      await tx.table('budgets').toCollection().modify((b: any) => {
        if (!b.periodType) {
          b.periodType = 'custom';
        }
        if (!b.categoryIds) {
          b.categoryIds = [];
        }
      });
    });

    this.version(14).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, group, isDefault, archived, updatedAt, deleted',
      budgets: 'id, ledgerId, periodType, startDate, endDate, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async tx => {
      await tx.table('budgets').toCollection().modify((b: any) => {
        if (!b.tierHistory) {
          b.tierHistory = [];
        }
        if (!b.periodOverrides) {
          b.periodOverrides = {};
        }
      });
    });

    this.version(15).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, group, isDefault, archived, updatedAt, deleted',
      budgets: 'id, ledgerId, ruleId, periodType, periodKey, startDate, endDate, updatedAt, deleted',
      budget_rules: 'id, ledgerId, periodType, isActive, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    }).upgrade(async tx => {
      const allBudgets = await tx.table('budgets').toArray();
      const today = new Date();
      const currentYear = today.getFullYear();
      const currentMonth = today.getMonth() + 1;
      const currentMonthKey = `${currentYear}-${String(currentMonth).padStart(2, '0')}`;
      const currentYearKey = String(currentYear);

      for (const b of allBudgets) {
        if (b.periodType === 'monthly') {
          const ruleId = uuidv4();
          await tx.table('budget_rules').add({
            id: ruleId,
            ledgerId: b.ledgerId,
            name: b.name,
            amount: b.amount,
            periodType: 'monthly',
            categoryIds: b.categoryIds || [],
            isActive: true,
            lastGeneratedPeriod: currentMonthKey,
            createdAt: b.createdAt || new Date().toISOString(),
            updatedAt: b.updatedAt || new Date().toISOString(),
            deleted: b.deleted || false,
          });

          const lastDay = new Date(currentYear, currentMonth, 0).getDate();
          await tx.table('budgets').update(b.id, {
            ruleId,
            periodKey: currentMonthKey,
            startDate: `${currentMonthKey}-01`,
            endDate: `${currentMonthKey}-${String(lastDay).padStart(2, '0')}`,
          });
        } else if (b.periodType === 'yearly') {
          const ruleId = uuidv4();
          await tx.table('budget_rules').add({
            id: ruleId,
            ledgerId: b.ledgerId,
            name: b.name,
            amount: b.amount,
            periodType: 'yearly',
            categoryIds: b.categoryIds || [],
            isActive: true,
            lastGeneratedPeriod: currentYearKey,
            createdAt: b.createdAt || new Date().toISOString(),
            updatedAt: b.updatedAt || new Date().toISOString(),
            deleted: b.deleted || false,
          });

          await tx.table('budgets').update(b.id, {
            ruleId,
            periodKey: currentYearKey,
            startDate: `${currentYearKey}-01-01`,
            endDate: `${currentYearKey}-12-31`,
          });
        }
      }
    });

    this.version(16).stores({
      ledgers: 'id, isDefault, updatedAt, deleted',
      transactions: 'id, displayId, ledgerId, budgetId, date, type, accountId, toAccountId, updatedAt, deleted',
      categories: 'id, ledgerId, type, isDefault, updatedAt, deleted',
      accounts: 'id, ledgerId, type, group, isDefault, archived, updatedAt, deleted',
      budgets: 'id, ledgerId, ruleId, periodType, periodKey, startDate, endDate, updatedAt, deleted',
      budget_rules: 'id, ledgerId, periodType, isActive, updatedAt, deleted',
      exchange_rates: 'currency, updatedAt',
    });

    this.version(17).stores({
      transactions: 'id, displayId, ledgerId, budgetId, reimbursementStatus, reimbursementContactId, date, type, accountId, toAccountId, updatedAt, deleted',
    });

    this.version(18).stores({
      transactions: 'id, displayId, ledgerId, parentId, budgetId, reimbursementStatus, reimbursementContactId, date, type, accountId, toAccountId, updatedAt, deleted',
    });

    this.version(19).stores({
      transactions: 'id, displayId, ledgerId, parentId, settlementId, splitGroupId, budgetId, reimbursementStatus, reimbursementContactId, date, type, accountId, toAccountId, updatedAt, deleted',
    });

    this.version(20).stores({
      transactions: 'id, displayId, ledgerId, category, parentId, settlementId, splitGroupId, budgetId, reimbursementStatus, reimbursementContactId, reimbursementIncomeTxId, date, type, accountId, toAccountId, updatedAt, deleted, [ledgerId+date], [ledgerId+type], [ledgerId+category]',
      categories: 'id, ledgerId, type, isDefault, archived, isSystem, updatedAt, deleted, [ledgerId+type], [ledgerId+archived]',
      accounts: 'id, ledgerId, type, group, isDefault, archived, updatedAt, deleted, [ledgerId+type], [ledgerId+archived]',
      budgets: 'id, ledgerId, ruleId, periodType, periodKey, startDate, endDate, updatedAt, deleted, [ledgerId+periodKey], [ruleId+periodKey]',
      budget_rules: 'id, ledgerId, periodType, isActive, updatedAt, deleted, [ledgerId+isActive]',
    });

    this.version(21).stores({
      contacts: 'id, ledgerId, name, group, currency, archived, updatedAt, deleted, [ledgerId+archived]',
    }).upgrade(async tx => {
      // 自動將舊 accounts 表中 type === 'contact' 的聯絡人遷移至獨立 contacts 表
      const allAccounts = await tx.table('accounts').toArray();
      const contactRecords: any[] = [];
      const contactIdsToDelete: string[] = [];

      for (const acc of allAccounts) {
        if (acc.type === 'contact') {
          contactRecords.push({
            id: acc.id,
            ledgerId: acc.ledgerId,
            name: acc.name,
            group: acc.group || 'personal',
            currency: acc.currency,
            archived: acc.archived || false,
            createdAt: acc.createdAt || new Date().toISOString(),
            updatedAt: acc.updatedAt || new Date().toISOString(),
            deleted: acc.deleted || false,
          });
          contactIdsToDelete.push(acc.id);
        }
      }

      if (contactRecords.length > 0) {
        await tx.table('contacts').bulkAdd(contactRecords);
        await tx.table('accounts').bulkDelete(contactIdsToDelete);
      }
    });

    this.version(22).stores({
      transactions: 'id, displayId, ledgerId, category, splitGroupId, budgetId, date, type, accountId, toAccountId, updatedAt, deleted, [ledgerId+date], [ledgerId+type], [ledgerId+category]',
    });

    this.version(23).stores({
      balance_snapshots: 'id, ledgerId, walletId, periodKey, [ledgerId+periodKey], [walletId+periodKey]',
    });
  }
}

export const db = new ZenanceDatabase();
